export const characters = [
    {
      name: { ja: "マリオ", en: "Mario" },
      type: "オールラウンド",
      stats: { speed: 3.5, power: 3.5, control: 3.5, spin: 1.5 },
      special: { ja: "なし", en: "None" },
      text: { ja: "すべての能力が高く、どんな相手やどんなコートでも有利にたたかえるオールラウンドなスタープレイヤー。", en: "A star player who excels in all areas. Always ready for a challenge!" },
      image: "assets/character_icons/mario.webp",
    },
    {
      name: { ja: "ルイージ", en: "Luigi" },
      type: "オールラウンド",
      stats: { speed: 3, power: 4, control: 2.5, spin: 1.5 },
      special: { ja: "強打スライスボレー強化", en: "Enhanced Power Slice Volley" },
      text: { ja: "ボレーが得意な万能プレイヤーでネット際につめるクセがある。B→Bで打つボレーが特に強い", en: "Specializes in volleys and feels right at home close to the net. Powerful slice shot B→B is extra strong." },
      image: "assets/character_icons/luigi.webp",
    },
    {
      name: { ja: "ピーチ", en: "Peach" },
      type: "テクニック",
      stats: { speed: 1, power: 1.5, control: 5, spin: 2 },
      special: { ja: "なし", en: "None" },
      text: { ja: "最高のボールコントロールと評判。コート端ぎりぎりに入るような精度の高いショットに誰もがおどろく", en: "Expertly lands shots right at the court's edge with unrivaled accuracy." },
      image: "assets/character_icons/peach.webp",
    },
    {
      name: { ja: "デイジー", en: "Daisy" },
      type: "オールラウンド",
      stats: { speed: 2, power: 3, control: 3, spin: 2 },
      special: { ja: "強打トップボレー強化", en: "Enhanced Power Topspin Volley" },
      text: { ja: "パワーとコントロールがバランスよく安定したプレイは評価が高い。A→Aで打つボレーが特に強い", en: "Known for consistent power and control. Powerful topspin shot A→A is extra strong." },
      image: "assets/character_icons/daisy.webp",
    },
    {
      name: { ja: "ロゼッタ", en: "Rosalina" },
      type: "トリッキー",
      stats: { speed: 3.5, power: 3.5, control: 3.5, spin: 3.5 },
      special: { ja: "ロブ強化", en: "Stronger Lobs" },
      text: { ja: "力強いショットとスピンで圧倒する。ネット際の相手の上をぬくロブは曲がる軌道で流れ星のように落ちる", en: "Overwhelms with powerful shots and heavy spin. Her lobs that sail over net players curve and drop like a shooting star.※To be confirmed after release." },
      image: "assets/character_icons/rosetta.webp",
    },
    {
      name: { ja: "ポリーン", en: "Pauline" },
      type: "スピード",
      stats: { speed: 5, power: 1.5, control: 3, spin: 1.5 },
      special: { ja: "なし", en: "None" },
      text: { ja: "コート上のスピードスター。上品なたたずまいながら遠くの球にもあきらめず追いつく姿には人気がある", en: "A speed star on the court. Despite her elegant style, she never gives up on far balls—fans love it.※To be confirmed after release." },
      image: "assets/character_icons/pauline.webp",
    },
    {
      name: { ja: "ワリオ", en: "Wario" },
      type: "パワー",
      stats: { speed: 2.5, power: 5, control: 2, spin: 1 },
      special: { ja: "トップチャージ高速化", en: "Faster Topspin Charge" },
      text: { ja: "パワフルで意外にすばやい。Aで打てるトップスピンを早くチャージできる", en: "Powerful and surprisingly quick. Can charge the Topspin A faster.※To be confirmed after release." },
      image: "assets/character_icons/wario.webp",
    },
    {
      name: { ja: "ワルイージ", en: "Waluigi" },
      type: "ディフェンス",
      stats: { speed: 1, power: 2.5, control: 1, spin: 2 },
      special: { ja: "フラットボレー強化", en: "Enhanced Flat Volley" },
      text: { ja: "長い手足での広い守備範囲が強み。ネット際では評判以上の力を見せる。Y→Yで打つボレーが特に強い", en: "Long limbs give huge defensive range. At the net, it’s stronger than you’d expect. Y→Y volleys are especially strong.※To be confirmed after release." },
      image: "assets/character_icons/waluigi.webp",
    },
    {
      name: { ja: "キノピオ", en: "Toad" },
      type: "スピード",
      stats: { speed: 5, power: 2, control: 2, spin: 1.5 },
      special: { ja: "なし", en: "None" },
      text: { ja: "キノコ王国を支えるために走り回るがんばり屋。ボールに向かって走る動き出しの速さには定評がある", en: "A hard worker who is quick to lend a hand around the Mushroom Kingdom. No one can get to the ball faster." },
      image: "assets/character_icons/kinopio.webp",
    },
    {
      name: { ja: "キノピコ", en: "Toadette" },
      type: "テクニック",
      stats: { speed: 1, power: 1, control: 5, spin: 3 },
      special: { ja: "なし", en: "None" },
      text: { ja: "左右にしっかり角度をつけるアングルショットが得意ワザ。相手をふりまわすテニススタイル", en: "Specialty: Angled-shot specialist skilled at catching opponents off balance." },
      image: "assets/character_icons/kinopico.webp",
    },
    {
      name: { ja: "チコ", en: "Luma" },
      type: "テクニック",
      stats: { speed: 2, power: 1.5, control: 4.5, spin: 2 },
      special: { ja: "ライジング時、各ショット強化", en: "Boosted shots on rising hits" },
      text: { ja: "ふわふわと移動する銀河の星の子。ボールがバウンドした瞬間を打つライジングショットが特に強い", en: "Galaxy denizen who floats around the court. Returns are extra strong if hit right when the ball bounces." },
      image: "assets/character_icons/chico.webp",
    },
    {
      name: { ja: "ヨッシー", en: "Yoshi" },
      type: "スピード",
      stats: { speed: 5, power: 2, control: 2.5, spin: 2 },
      special: { ja: "なし", en: "None" },
      text: { ja: "コート上をすばやく駆け回ってボールを打ち返す足の速さが自慢。ストローク勝負でねばるのが得意", en: "Proud of its quick feet, darting around the court to return shots. Great at grinding out stroke rallies.※To be confirmed after release." },
      image: "assets/character_icons/yoshi.webp",
    },
    {
      name: { ja: "クッパ", en: "Bowser" },
      type: "パワー",
      stats: { speed: 2, power: 5, control: 2.5, spin: 0.5 },
      special: { ja: "ストローク時のトップ強化", en: "Boosted topspin on strokes" },
      text: { ja: "最強のパワーをほこる。全力で打ったトップスピンには誰もがふきとぶ。A→Aで打つストロークが特に強い", en: "Boasts the strongest power. Full-force topspin sends anyone flying. A→A strokes are especially strong.※To be confirmed after release." },
      image: "assets/character_icons/koopa.webp",
    },
    {
      name: { ja: "クッパJr.", en: "Bowser Jr." },
      type: "トリッキー",
      stats: { speed: 3.5, power: 2, control: 3.5, spin: 4 },
      special: { ja: "なし", en: "None" },
      text: { ja: "イタズラ好きなクッパの息子。こっそり練習したトップスピンはクセのついた打ち方でとっても曲がる", en: "Bowser’s mischievous son. His secretly practiced topspin has a quirky swing and bends a lot.※To be confirmed after release." },
      image: "assets/character_icons/koopa-jr.webp",
    },
    {
      name: { ja: "ドンキーコング", en: "Donkey Kong" },
      type: "パワー",
      stats: { speed: 3.0, power: 5, control: 3.5, spin: 1 },
      special: { ja: "ストローク時、強打スライスに押し出し付与(スライスで返球されると無効)", en: "Power Slice strokes add pushback (canceled if returned with a slice)." },
      text: { ja: "陽気で力持ちなジャングルの王者。B→Bで打つストロークが特に強くスライスで打ち返さないとふきとぶ", en: "The cheerful, strong king of the jungle. B→B strokes are especially powerful—return with slice or get blown away.※To be confirmed after release." },
      image: "assets/character_icons/donkey-kong.webp",
    },
    {
      name: { ja: "テレサ", en: "Boo" },
      type: "トリッキー",
      stats: { speed: 3.5, power: 1, control: 2.5, spin: 5 },
      special: { ja: "なし", en: "None" },
      text: { ja: "大きく曲がる下ボタンのスライスサーブでおどろかせるのが好き。よく曲がるスライスには根強いファンがいる", en: "Known for a surprisingly wide-curving B slice serve that keeps opponents on their toes." },
      image: "assets/character_icons/teresa.webp",
    },
    {
      name: { ja: "ヘイホー", en: "Shy Guy" },
      type: "テクニック",
      stats: { speed: 2, power: 2.5, control: 4.5, spin: 1.5 },
      special: { ja: "ストローク時、強打トップコントロール強化", en: "Improved control for Power Topspin strokes" },
      text: { ja: "コートの端をねらうのが得意なテクニックタイプ。A→Aで打つストロークでもコート端をねらえる", en: "A technique type that loves targeting the lines. Even A→A strokes can aim for the edge of the court.※To be confirmed after release." },
      image: "assets/character_icons/heyho.webp",
    },
    {
      name: { ja: "ノコノコ", en: "Koopa Troopa" },
      type: "スピード",
      stats: { speed: 4.5, power: 2, control: 3, spin: 2.5 },
      special: { ja: "ドロップチャージ速度向上", en: "Faster Drop Shot Charge" },
      text: { ja: "コウラに入ってすばやく移動する。B→Aで打てるドロップショットを早くチャージできる", en: "Hustles around the court in a spinning shell. Drop shot B→A charges fast." },
      image: "assets/character_icons/nokonoko.webp",
    },
    {
      name: { ja: "カメック", en: "Kamek" },
      type: "トリッキー",
      stats: { speed: 4, power: 1.5, control: 1.5, spin: 4.5 },
      special: { ja: "なし", en: "None" },
      text: { ja: "クッパの手下のまほうつかい。クセのある曲がるショットが得意でトップスピンもスライスも曲がる", en: "Bowser’s minion magician. Excels at tricky bending shots—both topspin and slice can curve.※To be confirmed after release." },
      image: "assets/character_icons/kameck.webp",
    },
    {
      name: { ja: "ガボン", en: "Spike" },
      type: "パワー",
      stats: { speed: 3.5, power: 5, control: 2, spin: 0.5 },
      special: { ja: "なし", en: "None" },
      text: { ja: "のんびりしているが力持ち。体よりも大きなラケットを振り回す。パワータイプの中でもバランスが良い", en: "Easygoing but strong. Swings a racket bigger than its body. A well-balanced power type.※To be confirmed after release." },
      image: "assets/character_icons/gabon.webp",
    },
    {
      name: { ja: "ディディーコング", en: "Diddy Kong" },
      type: "スピード",
      stats: { speed: 5, power: 2.5, control: 2.5, spin: 3 },
      special: { ja: "スライスチャージ速度向上", en: "Faster Slice Charge" },
      text: { ja: "すばしっこくボールに追いつける。Bで打てるスライスを早くチャージできる", en: "Quick enough to reach the ball easily. Can charge the Slice B faster.※To be confirmed after release." },
      image: "assets/character_icons/diddy-kong.webp",
    },
    {
      name: { ja: "ワンワン", en: "Chain Chomp" },
      type: "パワー",
      stats: { speed: 2.5, power: 5, control: 3, spin: 0 },
      special: { ja: "スマッシュ返球時の押し出し無効", en: "No pushback when returning smashes" },
      text: { ja: "かたい体はだれよりも重い。スマッシュでもふきとばされない。力まかせでショットは全く曲がらない", en: "The heftiest of them all! Won't be pushed back, even by a Star Shot. Can't add curve to any shots." },
      image: "assets/character_icons/wanwan.webp",
    },
    {
      name: { ja: "キャサリン", en: "Birdo" },
      type: "オールラウンド",
      stats: { speed: 4, power: 3.5, control: 2.5, spin: 1.5 },
      special: { ja: "フラットチャージ速度向上", en: "Faster Flat Charge" },
      text: { ja: "安定したプレイでコート上を舞う。Yで打てるフラットを早くチャージできる", en: "Dances across the court with steady play. Can charge the Flat shot Y faster.※To be confirmed after release." },
      image: "assets/character_icons/catherine.webp",
    },
    {
      name: { ja: "パタパタ", en: "Koopa Paratroopa" },
      type: "テクニック",
      stats: { speed: 4, power: 2, control: 5, spin: 2.5 },
      special: { ja: "ロブチャージ速度向上", en: "Faster Lob Charge" },
      text: { ja: "コート端ぎりぎりをねらうのが得意。A→Bで打てるロブを早くチャージできる", en: "Skilled at landing shots at the court's edge. Lob shot A→B is quick to charge." },
      image: "assets/character_icons/patapata.webp",
    },
    {
      name: { ja: "ボスパックン", en: "Petey Piranha" },
      type: "パワー",
      stats: { speed: 2.5, power: 5, control: 3.5, spin: 1.5 },
      special: { ja: "フラットでNICEサーブ時強化、それ以外は弾速弱化。ストローク時、フラット強化", en: "Flat: boosted on NICE serves, otherwise slower. Flat strokes boosted." },
      text: { ja: "NICEでフラットサーブが打てると最速だが失敗するとヘロヘロ球に。Y→Yで打つストロークが特に強い", en: "Land a NICE flat serve for top speed, but miss and it becomes a weak floater. Y→Y strokes are especially strong.※To be confirmed after release." },
      image: "assets/character_icons/boss-packun.webp",
    },
    {
      name: { ja: "パックンフラワー", en: "Piranha Plant" },
      type: "トリッキー",
      stats: { speed: 3.0, power: 1, control: 4, spin: 1.5 },
      special: { ja: "トップが高弾道かつはねる", en: "Topspin has a high arc and extra bounce" },
      text: { ja: "鉢が重くてもテニスをしたい。全身をひねって打つトップスピンはだれよりも高弾道ではねる", en: "Determined to play despite being potted. No one's topspin shots bounce higher!" },
      image: "assets/character_icons/packun-flower.webp",
    },
    {
      name: { ja: "ブンブン", en: "Boom Boom" },
      type: "ディフェンス",
      stats: { speed: 2, power: 4, control: 2.5, spin: 0.5 },
      special: { ja: "左右移動が速く、前後移動は遅い", en: "Fast side-to-side movement, slow forward/back movement" },
      text: { ja: "大きな両手で守備範囲が広い。左右の移動は速いが前後の移動はとてもおそいという弱点がある", en: "Wide defensive range thanks to huge hands. Side-to-side movement is fast, but forward/back movement is very slow.※To be confirmed after release." },
      image: "assets/character_icons/bunbun.webp",
    },
    {
      name: { ja: "ゲッソー", en: "Blooper" },
      type: "トリッキー",
      stats: { speed: 3.5, power: 0.5, control: 3.5, spin: 4 },
      special: { ja: "スライスが高弾道", en: "Slice travels in a high arc" },
      text: { ja: "バケツの水をあびてなんとか出場。やわらかい体で打ち出すスライスは高い弾道でするどく曲がる", en: "Competing on land through the power of a water bucket. Hits with sharp curve and high trajectory." },
      image: "assets/character_icons/gesso.webp",
    },
    {
      name: { ja: "ほねクッパ", en: "Dry Bowser" },
      type: "ディフェンス",
      stats: { speed: 2, power: 4.5, control: 1, spin: 1 },
      special: { ja: "バックハンド時、スライス強化", en: "Stronger backhand slice" },
      text: { ja: "相手を圧倒するパワーは健在。バックハンドのスライスが強力でフォアハンドよりよく曲がる", en: "That overwhelming power is still there. The backhand slice is strong and curves more than the forehand.※To be confirmed after release." },
      image: "assets/character_icons/hone-koopa.webp",
    },
    {
      name: { ja: "カロン", en: "Dry Bones" },
      type: "トリッキー",
      stats: { speed: 1.5, power: 3, control: 3, spin: 3.5 },
      special: { ja: "ドロップが曲がる", en: "Curving drop shot" },
      text: { ja: "コウラに入って移動するがノコノコとちがってけっこうおそい。B→Aのドロップショットが曲がる", en: "Moseys around the court in a slow-moving shell. Drop shot B→A curves." },
      image: "assets/character_icons/karon.webp",
    },
    {
      name: { ja: "ベビィマリオ", en: "Baby Mario" },
      type: "オールラウンド",
      stats: { speed: 3.5, power: 2.5, control: 3, spin: 2.5 },
      special: { ja: "なし", en: "None" },
      text: { ja: "ベビィのころのマリオ。すべての能力が安定して高い。足りないパワーはスピンでおぎなう", en: "Mario as a baby. Solid, well-balanced stats. Makes up for lower power with spin.※To be confirmed after release." },
      image: "assets/character_icons/baby-mario.webp",
    },
    {
      name: { ja: "ベビィルイージ", en: "Baby Luigi" },
      type: "オールラウンド",
      stats: { speed: 2.5, power: 3, control: 2.5, spin: 1.5 },
      special: { ja: "強打スライスボレー強化", en: "Enhanced Power Slice Volley" },
      text: { ja: "ベビィのころのルイージ。マリオと組むために練習したボレーが得意でB→Bのボレーが特に強い", en: "Honed volley skills to team up with Mario. Powerful slice shot B→B is extra strong." },
      image: "assets/character_icons/baby-luigi.webp",
    },
    {
      name: { ja: "ベビィピーチ", en: "Baby Peach" },
      type: "テクニック",
      stats: { speed: 1, power: 1, control: 5, spin: 2 },
      special: { ja: "なし", en: "None" },
      text: { ja: "ベビィのころのピーチ。コート端ぎりぎりに入るような精度の高いショットが得意", en: "Lands shots just as expertly as adult counterpart." },
      image: "assets/character_icons/baby-peach.webp",
    },
    {
      name: { ja: "ハナチャン", en: "Wiggler" },
      type: "ディフェンス",
      stats: { speed: 5, power: 4, control: 1.5, spin: 0.5 },
      special: { ja: "切り替えしが苦手", en: "Slow to change direction" },
      text: { ja: "たくさんの足で前進するのが得意。スピードが乗ると速いものの方向転換はニガテで止まりづらい", en: "Easily scuttles forward with many legs. Quick once up to speed, but not great at changing directions." },
      image: "assets/character_icons/hana-chan.webp",
    },
    {
      name: { ja: "トッテン", en: "Nabbit" },
      type: "スピード",
      stats: { speed: 5, power: 1.5, control: 2.5, spin: 2.5 },
      special: { ja: "フォアハンド強化、バックハンド弱化", en: "Stronger forehand, weaker backhand" },
      text: { ja: "逃げ足がとっても速い。フォアハンドのショットは強いが袋がジャマでバックハンドは弱い", en: "Takes off like a jet. Strong forehand shot. Bag gets in the way of backhands." },
      image: "assets/character_icons/totten.webp",
    },
    {
      name: { ja: "クリボー", en: "Goomba" },
      type: "オールラウンド",
      stats: { speed: 4, power: 2, control: 3.5, spin: 1.5 },
      special: { ja: "なし", en: "None" },
      text: { ja: "簡単にやられがちなクッパの手下。ラケットくわえてテニスに挑戦。クリボーでもがんばれば勝てますか？", en: "A trusty, if easily defeated, minion who's stepping up to the court-racket in mouth!" },
      image: "assets/character_icons/kuribo.webp",
    },
    {
      name: { ja: "ベビィワリオ", en: "Baby Wario" },
      type: "パワー",
      stats: { speed: 2.5, power: 4.5, control: 2, spin: 1 },
      special: { ja: "トップチャージ速度向上", en: "Faster Topspin Charge" },
      text: { ja: "ベビィのころのワリオ。Aで打てるトップスピンを早くチャージできる", en: "Wario as a baby. Can charge the Topspin A faster.※To be confirmed after release." },
      image: "assets/character_icons/baby-wario.webp",
    },
    {
      name: { ja: "ベビィワルイージ", en: "Baby Waluigi" },
      type: "ディフェンス",
      stats: { speed: 1.5, power: 2, control: 1.5, spin: 2 },
      special: { ja: "フラットボレー強化", en: "Enhanced Flat Volley" },
      text: { ja: "ベビィのころのワルイージ。スライドフットワークで広く守る。Y→Yで打つボレーが特に強い", en: "Waluigi as a baby. Uses sliding footwork to cover wide. Y→Y volleys are especially strong.※To be confirmed after release." },
      image: "assets/character_icons/baby-waluigi.webp",
    },
  ];
  
  export const rackets = [
    {
     name: { ja: "マイラケット", en: "My Racket" },
     category: "その他",
     timing: "即時",
     effect: { ja: "高弾速の球を打つ。バウンドした場所付近に衝撃波が発生し、触れると小時間行動不可+ダメージ", en: "Hits a shot with boosted ball speed. (To be confirmed after release.)" },
     text: { ja: "特別な力はないが、手になじんで使いやすい。それぞれのお気に入りのラケット", en: "" },
     image: "assets/racket_icons/my_racket.svg",
    },
    {
      name: { ja: "ファイアラケット", en: "Flame Racket" },
      category: "妨害",
      timing: "バウンド時",
      effect: { ja: "十字方向に5つの炎を設置。触れると短時間ショット不可 + 強制移動 + ダメージ。", en: "Places five flames in a cross pattern. Touching them briefly prevents shots, forces movement, and deals damage." },
      text: { ja: "バウンドした場所から炎をまわりにまきちらす。ふれるとアチチ！と走りまわる。", en: "It scatters flames around the bounce point. Touch one and you start running around in a panic!" },
      image: "assets/racket_icons/fire_racket.webp",
    },
    {
      name: { ja: "アイスラケット", en: "Ice Racket" },
      category: "妨害",
      timing: "即時",
      effect: { ja: "氷の床を設置。踏んでいる間滑って切り替えししづらくなる。強打をすると短時間行動不可", en: "Creates an icy floor. While on it, you slide and struggle to change direction. Using a power shot briefly prevents actions." },
      text: { ja: "バウンドした場所に氷の床を作る。氷で足が滑って強いショットを打ち返すと転ぶ", en: "It creates an icy floor at the bounce point. You slip on the ice, and trying to return a strong shot can make you fall." },
      image: "assets/racket_icons/ice_racket.svg",
    },
    {
      name: { ja: "サンダーラケット", en: "Lightning Racket" },
      category: "妨害",
      timing: "バウンド時",
      effect: { ja: "円状の雷の床を設置。触れると中時間操作不能+ダメージ", en: "Places a ring of lightning. Touch it and you’re unable to control your character for a medium duration and take damage." },
      text: { ja: "バウンドした場所に雷が発生。ふれると体がビリビリしてしばらく動けなくなる。", en: "Lightning strikes at the bounce point. Touch it and your body is shocked, leaving you unable to move for a while." },
      image: "assets/racket_icons/sunder_racket.webp",
    },
    {
      name: { ja: "ヒューゴーラケット", en: "Ty-Foo Racket" },
      category: "妨害",
      timing: "バウンド時",
      effect: { ja: "動く竜巻を設置。触れると小時間操作不能+ダメージ。ボールが当たると軌道変化。", en: "Places a moving tornado. Touching it briefly disables controls and deals damage. If the ball hits it, the ball’s trajectory changes." },
      text: { ja: "バウンドした場所に強風が発生。ふれるとふきとばされる。ボールが当たると軌道が変わる。", en: "A strong wind appears at the bounce point. If touched, you get blown away. Balls that hit it will change trajectory." },
      image: "assets/racket_icons/hyou-go_racket.webp",
    },
     {
     name: { ja: "ドロドロラケット", en: "Mud Racket" },
     category: "妨害",
     timing: "バウンド時",
     effect: { ja: "ドロの床を設置。踏んでいる間移動速度低下+ダメージ。", en: "Creates a muddy floor. While standing on it, movement speed drops and you take damage." },
     text: { ja: "バウンドした場所にドロの床を作って移動づらくなる。ボールもはねづらく体力も減る。", en: "It creates a muddy floor at the bounce point, making movement difficult. The ball also bounces less, and your stamina drains." },
     image: "assets/racket_icons/dorodoro_racket.webp",
     },
    {
     name: { ja: "マメキノコラケット", en: "Mini Mushroom Racket" },
     category: "妨害",
     timing: "バウンド時",
     effect: { ja: "縦に動く4列のマメキノコを設置。触れると体が小さくなりボールに追いつきづらくなる。", en: "Places four vertical-moving columns of Mini Mushrooms. Touching them shrinks you and makes it harder to reach the ball." },
     text: { ja: "バウンドした場所のまわりにマメキノコを出現させる。ふれると体が小さくなる", en: "Mini Mushrooms appear around the bounce point. Touch one and your body shrinks." },
     image: "assets/racket_icons/mamekinoko_racket.webp",
    },
    {
        name: { ja: "ファイアフラワーラケット", en: "Fire Flower Racket" },
        category: "妨害",
        timing: "即時",
        effect: { ja: "打球時ファイアボールを2発ばらまく。チャージすると3発、スーパーチャージだと4発ばらまく。触れると短時間ショット不可 + 強制移動 + ダメージ", en: "" },
        text: { ja: "使うとしばらくの間打つときにファイアボールを発生させる。ふれるとアチチ!と走り回る", en: "For a while after use, your shots spawn fireballs. Touching them makes players run around in panic." },
        image: "assets/racket_icons/fireflower_racket.webp",
      },
      {
        name: { ja: "アイスフラワーラケット", en: "Ice Flower Racket" },
        category: "妨害",
        timing: "即時",
        effect: { ja: "打球時アイスボールを2発ばらまく。チャージすると3発、スーパーチャージだと4発ばらまく。触れると短時間行動不可 + ダメージ", en: "" },
        text: { ja: "使うとしばらくの間打つときにアイスボールを発生させる。ふれるとこおって動けなくなる", en: "For a while after use, your shots spawn ice balls. Touch one and you freeze, unable to move." },
        image: "assets/racket_icons/iceflower_racket.webp",
      },
      {
        name: { ja: "スターラケット", en: "Star Racket" },
        category: "強化",
        timing: "即時",
        effect: { ja: "妨害を受けない無敵状態になり、スピードも上がる", en: "" },
        text: { ja: "使うとしばらくの間コート上のジャマを受け付けない無敵になる。移動も少し速くなる", en: "Using it grants temporary invincibility against court hazards. Your movement speed also increases slightly." },
        image: "assets/racket_icons/star_racket.webp",
      },
      {
        name: { ja: "たつまきラケット", en: "Tornado Racket" },
        category: "妨害",
        timing: "即時",
        effect: { ja: "打った地点から前方に進む竜巻を発生。触れると小時間操作不能+ダメージ。ボールが当たると軌道変化", en: "" },
        text: { ja: "使うとしばらくの間打つときにたつまきを発生させる。ふれたものはふきとばされる", en: "For a while after use, your shots create tornadoes. Anything they touch gets blown away." },
        image: "assets/racket_icons/tatumaki_racket.webp",
      },
    {
      name: { ja: "サンボラケット", en: "Pokey Racket" },
      category: "妨害",
      timing: "バウンド時",
      effect: { ja: "サンボを設置。ボールやプレイヤーが当たると周囲に身体をバラまく。触れると小時間操作不能+ダメージ。", en: "Places a Pokey. If the ball or a player hits it, it scatters pieces around. Touching it briefly disables controls and deals damage." },
      text: { ja: "バウンドした場所にサンボが出現させる。ボールを当てるとくずれる", en: "A Pokey appears at the bounce point. It collapses when hit by the ball." },
      image: "assets/racket_icons/sanbo_racket.webp",
    },
    {
      name: { ja: "シャドウラケット", en: "Shadow Racket" },
      category: "強化",
      timing: "即時",
      effect: { ja: "分身を自コートに生成。分身位置はプレイヤー位置に依存。分身は自動で返球する。", en: "Creates a clone on your side. Its position depends on your position. It returns balls automatically." },
      text: { ja: "使うと自分の分身を作る。しばらくの間勝手にうごいてボールを打ち返してくれる", en: "Using it creates your clone. For a while, it moves on its own and returns balls for you." },
      image: "assets/racket_icons/shadow_racket.webp",
    },
    {
        name: { ja: "ファイアバーラケット", en: "Fire Bar Racket" },
        category: "妨害",
        timing: "バウンド時",
        effect: { ja: "円運動をするファイアバーを設置。触れると短時間ショット不可 + 強制移動 + ダメージ。", en: "" },
        text: { ja: "バウンドした場所にファイアバーを出現させる。ふれるとアチチ！と走り回る。", en: "A Fire Bar appears at the bounce point. Touch it and you run around in panic." },
        image: "assets/racket_icons/firebar_racket.webp",
      },
      {
        name: { ja: "フリーズラケット", en: "Freezing Racket" },
        category: "妨害",
        timing: "バウンド時",
        effect: { ja: "左右に3つずつ、氷を放射状に設置。触れると小時間行動不可 + ダメージ", en: "" },
        text: { ja: "バウンドした場所のまわりに氷をばらまく。ふれるとこおって動けなくなる", en: "It scatters ice around the bounce point. Touching it freezes you, leaving you unable to move." },
        image: "assets/racket_icons/frieze_racket.webp",
      },
      {
        name: { ja: "ビリキューラケット", en: "Amp Racket" },
        category: "妨害",
        timing: "即時",
        effect: { ja: "打ったボールをビリキューにし、バウンド時に設置。最大3個まで設置でき、ビリキュー同士の間に雷が発生する。雷か本体に触れると小時間行動不可 + ダメージ", en: "To be confirmed after release." },
        text: { ja: "使うとしばらくの間打つときにボールをビリキューに変える。ビリキュー同氏は雷でつながる。", en: "For a while after use, your shots turn balls into Amps. Amp balls connect to each other with lightning." },
        image: "assets/racket_icons/birikyu-_racket.webp",
      },
      {
        name: { ja: "カーブラケット", en: "Swerve Racket" },
        category: "強化",
        timing: "即時",
        effect: { ja: "トップ・スライス・ドロップ・ロブの各球種でよく曲がるようになる。ロブは着弾速度も高速化", en: "" },
        text: { ja: "使うとしばらくの間ショットを曲げる強化がつく。トップスピンやロブも曲がる", en: "For a while after use, your shots gain a curve effect. Topspin and lobs can curve too." },
        image: "assets/racket_icons/curve_racket.webp",
      },
      {
        name: { ja: "インクラケット", en: "Inky Racket" },
        category: "妨害",
        timing: "バウンド時",
        effect: { ja: "インクの床を設置。触れた後に打球すると自画面の一部が隠れる。カウンター時も都度小さなインクの床が設置される。床内でバウンドすると球が変化し、打ち返すと画面が一部隠れるが床は追加では設置されない。", en: "" },
        text: { ja: "前を見づらくするインクをまく。インク内で打ち返す時やインクがついたボールを打つ時も効果あり", en: "It sprays ink that makes it hard to see ahead. The effect also applies when returning inside ink or hitting an ink-covered ball." },
        image: "assets/racket_icons/ink_racket.webp",
      },
      {
        name: { ja: "バナナラケット", en: "Banana Racket" },
        category: "妨害",
        timing: "バウンド時",
        effect: { ja: "6本のバナナの皮を設置。触ると小時間行動不可+ダメージ。カウンター時も都度2本のバナナが設置される。バナナにボールが当たると除去される。", en: "" },
        text: { ja: "バウンドした時とカウンターした時にバナナの皮をまく。ふむとすべってころんでしまう。", en: "It drops banana peels on bounce and on counter shots. Step on one and you slip and fall." },
        image: "assets/racket_icons/banana_racket.webp",
      },
      {
        name: { ja: "かざんラケット", en: "Volcano Racket" },
        category: "妨害",
        timing: "バウンド時",
        effect: { ja: "火山口を設置。プレイヤー位置付近に円状の予告範囲が発生し、一定時間後に範囲内にいると短時間ショット不可 + 強制移動 + ダメージ", en: "" },
        text: { ja: "バウンドした場所に火山口を作って岩をふらせる。ふれるとアチチ!と走りまる", en: "It creates a crater at the bounce point that rains down rocks. Touching them makes you run around in panic." },
        image: "assets/racket_icons/kazan_racket.webp",
      },
      {
        name: { ja: "おばけラケット", en: "Boo Racket" },
        category: "強化",
        timing: "即時",
        effect: { ja: "自分の姿が相手に見えなくなり、打ったボールも途中で見えなくなる", en: "" },
        text: { ja: "使うとしばらくの間打ったボールと自分の姿が相手に見えなくなる", en: "For a while after use, the balls you hit and your character become invisible to the opponent." },
        image: "assets/racket_icons/obake_racket.webp",
      },
      {
        name: { ja: "ダッシュラケット", en: "Golden Dash Racket" },
        category: "強化",
        timing: "即時",
        effect: { ja: "飛びつきが出来る距離を大幅に強化する。通常の飛びつきとは異なり、ショットの種類も反映される。ショット時に飛びつきは強制されず、普段通りの行動も可能。逆方向への切り替えし最中やボールの方向に移動キーを入れていない場合は飛びつけない。", en: "" },
        text: { ja: "使うとしばらくの間すばやく飛びつける強化がつく。はなれたボールにも追いつける", en: "For a while after use, you gain a quick lunge boost, letting you reach balls that are farther away." },
        image: "assets/racket_icons/dash_racket.webp",
      },
      {
        name: { ja: "ブルラケット", en: "Chargin' Chuck Racket" },
        category: "妨害",
        timing: "即時",
        effect: { ja: "打球時にボールを変化させ、バウンド時の軌道が不規則になる。バウンドするまで変化は持続する(変化中に強化時間が終了しても同様)。", en: "" },
        text: { ja: "使うとしばらくの間打つ時にボールを違う形に変える。バウンドのときあちこちにはねる", en: "For a while after use, balls you hit change into a different shape. They bounce unpredictably in many directions." },
        image: "assets/racket_icons/bull_racket.webp",
      },
      {
        name: { ja: "トゲゾーラケット", en: "Spiny Racket" },
        category: "妨害",
        timing: "バウンド時",
        effect: { ja: "トゲゾーを3体設置(カウンター時は最大6匹)。プレイヤーにゆっくりと誘導し、触れると小距離押し出し + ダメージ。トゲゾーにボールが当たると除去される。", en: "" },
        text: { ja: "バウンドした場所にトゲゾーを出現させる。トゲゾーは歩いて近づいてくる", en: "A Spiny appears at the bounce point. It walks toward players as it approaches." },
        image: "assets/racket_icons/togezo_racket.webp",
      },
      {
        name: { ja: "マジックラケット", en: "Magic Racket" },
        category: "妨害",
        timing: "バウンド時",
        effect: { ja: "まほうの杖を設置。設置地点からプレイヤーに直線軌道で弾を発射。触れると小時間行動不可 + ダメージ + ラケットがフライパンになり、一定時間フラット以外の球種が使用不可になる", en: "" },
        text: { ja: "バウンドした場所にまほうの杖を出現させる。まほうにふれるとラケットが変化", en: "A magic wand appears at the bounce point. Touching the magic changes your racket." },
        image: "assets/racket_icons/magic_racket.svg",
      },
      {
        name: { ja: "キラーラケット", en: "Bullet Bill Racket" },
        category: "強化",
        timing: "即時",
        effect: { ja: "打球時ボールをキラーに変化させ、一定時間後高弾速になる。変化後速くなるタイミングは球種によって変化し、スマッシュだと即時。強化時はコントロールに制限がかかり、コート端を狙ったショットは不可", en: "" },
        text: { ja: "使うとしばらくの間打つ時にボールをkillerに変える。キラーは高速でまっすぐ飛ぶ", en: "For a while after use, balls you hit turn into Bullet Bills. Bullet Bills fly fast in a straight line." },
        image: "assets/racket_icons/killer_racket.svg",
      },
      {
        name: { ja: "ドッスンラケット", en: "Thwomp Racket" },
        category: "妨害",
        timing: "バウンド時",
        effect: { ja: "上空にドッスンを生成。落下地点付近にいると小時間行動不可+ダメージ。直撃するとK.O.。ボールがドッスンに当たると軌道が変化する。ダウン状態中さらに直撃すると長時間行動不可になるが、カウント状態は変化しない。", en: "" },
        text: { ja: "バウンドした場所にドッスンを出現させる。近づくとふみつぶされてしまう", en: "A Thwomp appears at the bounce point. Get close and you’ll be crushed." },
        image: "assets/racket_icons/dossun_racket.svg",
      },
      {
        name: { ja: "オシダシーラケット", en: "Shova Racket" },
        category: "妨害",
        timing: "即時",
        effect: { ja: "打球時、全ての球種で中距離をふきとばす強化状態になる。", en: "On return, you get knocked back a short distance. (To be confirmed after release.)" },
        text: { ja: "使うとしばらくの間相手をコート奥に押し出す強化がつく。ショットの威力も少しあがる。", en: "For a while after use, your shots gain a pushback effect that forces opponents deeper into the court. Shot power also rises slightly." },
        image: "assets/racket_icons/oshidasi_racket.svg",
      },
    {
      name: { ja: "メタルラケット", en: "Metal Racket" },
      category: "強化",
      timing: "即時",
      effect: { ja: "妨害を受けない無敵状態になり、ショット威力も上がる", en: "Become invincible and boost shot power." },
      text: { ja: "使うとしばらくの間コート上のジャマを受けないメタル状態に。ショット威力が少しあがる", en: "Using it puts you in a Metal state for a while, ignoring court hazards. Shot power increases slightly." },
      image: "assets/racket_icons/metal_racket.svg",
    },
    {
        name: { ja: "ハテナケット", en: "Question Racket" },
        category: "妨害",
        timing: "その他",
        effect: { ja: "使用する度、全ラケットからランダムで効果が発生", en: "Each use triggers a random effect from the full racket pool." },
        text: { ja: "ショットするまでどの効果が出るか分からない。使うたびに効果がかわる", en: "You won’t know which effect appears until you shoot. The effect changes every time you use it." },
        image: "assets/racket_icons/hatena_racket.svg",
      },
    {
      name: { ja: "ブーメランラケット", en: "Boomerang Racket" },
      category: "強化",
      timing: "即時",
      effect: { ja: "スイングモードのみ選択可能。プレイヤーの周りに円状に回るブーメランを設置し、短時間だけ自動返球できる。返球時は高速でよく曲がるスライスで打ち返す。", en: "" },
      text: { ja: "使うとしばらくの間自分のまわりをぐるぐるまわってボールを打ち返してくれる", en: "For a while after use, boomerangs spin around you and return balls on your behalf." },
      image: "assets/racket_icons/boomerang_racket.svg",
    },
  ];

export const tips = [
  {
    title: { ja: "フィーバーゲージ2本分が溜まるまでの目安時間", en: "Approximate time to fill two Fever gauges" },
    category: "仕様",
    verification: "検証中",
    content: { ja: "ラリーを継続している場合、フィーバーゲージ2本分が溜まるまでの目安は約○○秒。", en: "While rallying continuously, the rough time to fill two Fever gauges is about XX seconds (under verification)." },
  },
  {
    title: { ja: "フィーバーショット同士の打ち合い時の判定", en: "Judgment when returning Fever Shot with Fever Shot" },
    category: "実践知識",
    verification: "検証中",
    content: { ja: "フィーバーショットをフィーバーショットで返球すると、着弾位置によってはワンバウンドしてから打ち返す。", en: "When you return a Fever Shot with another Fever Shot, it is treated as if it bounced once." },
  },
];

  /** @type {{ date: { ja: string; en: string }; items: { ja: string; en: string }[] }[]} */
  export const changelog = [
    {
      date: { ja: "2025-02-07", en: "2025-02-07" },
      items: [
        { ja: "ロゼッタ/ベビィマリオ/ヘイホーのパラメータやテキストを修正\n", en: "Adjusted Rosetta/Baby Mario/Shy Guy parameters and text.\n" },
        { ja: "スマホとタブレットで、検索画面が崩れる不具合を修正\n", en: "Fixed a layout issue on the search screen on smartphones and tablets.\n" },
        { ja: "スマホの検索画面で特定数以上候補がある場合、スクロールする必要があった仕様を撤廃。\nスクロール無しで全件確認出来るよう変更", en: "Removed the old mobile behavior that required scrolling when there were many search candidates.\nNow all candidates can be viewed without scrolling." },
      ],
    },
    {
      date: { ja: "2025-02-08", en: "2025-02-08" },
      items: [
        { ja: "ラケット一覧を更新(体験版時点で分かる範囲のみ)", en: "Updated the racket list (within what was confirmed in the demo build)." },
        { ja: "検索画面の処理高速化", en: "Improved search screen performance." },
        { ja: "ラケット一覧の誤記を修正", en: "Fixed typos in the racket list." },
        { ja: "各パラメータを確認しやすいように、スマホ版の「全項目を見る」の挙動変更。", en: "Adjusted the mobile 'Show all' behavior to make each parameter easier to check." },
      ],
    },
    {
      date: { ja: "2025-02-09", en: "2025-02-09" },
      items: [
          { ja: "PC版に各項目へジャンプ出来るヘッダーを実装", en: "Implemented a PC header that allows jumping to each section." },
          { ja: "言語切り替え機能を実装", en: "Implemented language switch to English." }
      ],
    },
    {
        date: { ja: "2025-02-10", en: "2025-02-10" },
        items: [
            { ja: "ラケット一覧に動画再生機能を実装", en: "Implemented 'Watch effect video' function for rackets." },
            { ja: "お気に入り機能を実装し、フィルタにも対応", en: "Implemented favorite feature with filter support." },
            { ja: "Tier表作成機能を実装", en: "Implemented tier list creation function." }
        ],
      },
      {
        date: { ja: "2025-02-11", en: "2025-02-11" },
        items: [
            { ja: "Tipsを実装", en: "Implemented Tips." },
            { ja: "Tier表のアイコンを入れ替え出来るよう修正", en: "Updated so icons in the Tier table can be swapped." }
        ],
      },
  ];
  