export const characters = [
  {
    name: "マリオ",
    type: "オールラウンド",
    stats: { speed: 3.5, power: 3.5, control: 3.5, spin: 1.5 },
    special: "特になし",
    text: "すべての能力が高く、どんな相手やどんなコートでも有利にたたかえるオールラウンドなスタープレイヤー。",
    image: "assets/character_icons/mario.svg",
  },
  {
    name: "ルイージ",
    type: "オールラウンド",
    stats: { speed: 3, power: 4, control: 2.5, spin: 1.5 },
    special: "強打スライスボレー強化",
    text: "ボレーが得意な万能プレイヤーでネット際につめるクセがある。B→Bで打つボレーが特に強い",
    image: "assets/character_icons/luigi.svg",
  },
  {
    name: "ピーチ",
    type: "テクニック",
    stats: { speed: 1, power: 1.5, control: 5, spin: 2 },
    special: "特になし",
    text: "最高のボールコントロールと評判。コート端ぎりぎりに入るような精度の高いショットに誰もがおどろく",
    image: "assets/character_icons/peach.svg",
  },
  {
    name: "デイジー",
    type: "オールラウンド",
    stats: { speed: 2, power: 3, control: 3, spin: 2 },
    special: "強打トップボレー強化",
    text: "パワーとコントロールがバランスよく安定したプレイは評価が高い。A→Aで打つボレーが特に強い",
    image: "assets/character_icons/daisy.svg",
  },
  {
    name: "ロゼッタ",
    type: "トリッキー",
    stats: { speed: 4.5, power: 4.5, control: 4.5, spin: 4.5 },
    special: "ロブ強化",
    text: "力強いショットとスピンで圧倒する。ネット際の相手の上をぬくロブは曲がる軌道で流れ星のように落ちる",
    image: "assets/character_icons/rosetta.svg",
  },
  {
    name: "ポリーン",
    type: "スピード",
    stats: { speed: 5, power: 1.5, control: 3, spin: 1.5 },
    special: "特になし",
    text: "コート上のスピードスター。上品なたたずまいながら遠くの球にもあきらめず追いつく姿には人気がある",
    image: "assets/character_icons/pauline.svg",
  },
  {
    name: "ワリオ",
    type: "パワー",
    stats: { speed: 2.5, power: 5, control: 2, spin: 1 },
    special: "トップチャージ高速化",
    text: "パワフルで意外にすばやい。Aで打てるトップスピンを早くチャージできる",
    image: "assets/character_icons/wario.svg",
  },
  {
    name: "ワルイージ",
    type: "ディフェンス",
    stats: { speed: 1, power: 2.5, control: 1, spin: 2 },
    special: "フラットボレー強化",
    text: "長い手足での広い守備範囲が強み。ネット際では評判以上の力を見せる。Y→Yで打つボレーが特に強い",
    image: "assets/character_icons/waluigi.svg",
  },
  {
    name: "キノピオ",
    type: "スピード",
    stats: { speed: 5, power: 2, control: 2, spin: 1.5 },
    special: "特になし",
    text: "キノコ王国を支えるために走り回るがんばり屋。ボールに向かって走る動き出しの速さには定評がある",
    image: "assets/character_icons/kinopio.svg",
  },
  {
    name: "キノピコ",
    type: "テクニック",
    stats: { speed: 1, power: 1, control: 5, spin: 3 },
    special: "特になし",
    text: "左右にしっかり角度をつけるアングルショットが得意ワザ。相手をふりまわすテニススタイル",
    image: "assets/character_icons/kinopico.svg",
  },
  {
    name: "チコ",
    type: "テクニック",
    stats: { speed: 2, power: 1.5, control: 4.5, spin: 2 },
    special: "ライジング時、各ショット強化",
    text: "ふわふわと移動する銀河の星の子。ボールがバウンドした瞬間を打つライジングショットが特に強い",
    image: "assets/character_icons/chico.svg",
  },
  {
    name: "ヨッシー",
    type: "スピード",
    stats: { speed: 5, power: 2, control: 2.5, spin: 2 },
    special: "特になし",
    text: "コート上をすばやく駆け回ってボールを打ち返す足の速さが自慢。ストローク勝負でねばるのが得意",
    image: "assets/character_icons/yoshi.svg",
  },
  {
    name: "クッパ",
    type: "パワー",
    stats: { speed: 2, power: 5, control: 2.5, spin: 0.5 },
    special: "ストローク時のトップ強化",
    text: "最強のパワーをほこる。全力で打ったトップスピンには誰もがふきとぶ。A→Aで打つストロークが特に強い",
    image: "assets/character_icons/koopa.svg",
  },
  {
    name: "クッパJr.",
    type: "トリッキー",
    stats: { speed: 3.5, power: 2, control: 3.5, spin: 4 },
    special: "特になし",
    text: "イタズラ好きなクッパの息子。こっそり練習したトップスピンはクセのついた打ち方でとっても曲がる",
    image: "assets/character_icons/koopa-jr.svg",
  },
  {
    name: "ドンキーコング",
    type: "パワー",
    stats: { speed: 3.0, power: 5, control: 3.5, spin: 1 },
    special: "ストローク時、強打スライスに押し出し付与(スライスで返球されると無効)",
    text: "陽気で力持ちなジャングルの王者。B→Bで打つストロークが特に強くスライスで打ち返さないとふきとぶ",
    image: "assets/character_icons/donkey-kong.svg",
  },
  {
    name: "テレサ",
    type: "トリッキー",
    stats: { speed: 3.5, power: 1, control: 2.5, spin: 5 },
    special: "特になし",
    text: "大きく曲がる下ボタンのスライスサーブでおどろかせるのが好き。よく曲がるスライスには根強いファンがいる",
    image: "assets/character_icons/teresa.svg",
  },
  {
    name: "ヘイホー",
    type: "テクニック",
    stats: { speed: 3.0, power: 3.5, control: 2.5, spin: 3.5 },
    special: "ストローク時、強打トップコントロール強化",
    text: "コートの端をねらうのが得意なテクニックタイプ。A→Aで打つストロークでもコート端をねらえる",
    image: "assets/character_icons/heyho.svg",
  },
  {
    name: "ノコノコ",
    type: "スピード",
    stats: { speed: 4.5, power: 2, control: 3, spin: 2.5 },
    special: "ドロップチャージ速度向上",
    text: "コウラに入ってすばやく移動する。B→Aで打てるドロップショットを早くチャージできる",
    image: "assets/character_icons/nokonoko.svg",
  },
  {
    name: "カメック",
    type: "トリッキー",
    stats: { speed: 4, power: 1.5, control: 1.5, spin: 4.5 },
    special: "特になし",
    text: "クッパの手下のまほうつかい。クセのある曲がるショットが得意でトップスピンもスライスも曲がる",
    image: "assets/character_icons/kameck.svg",
  },
  {
    name: "ガボン",
    type: "パワー",
    stats: { speed: 3.5, power: 5, control: 2, spin: 0.5 },
    special: "特になし",
    text: "のんびりしているが力持ち。体よりも大きなラケットを振り回す。パワータイプの中でもバランスが良い",
    image: "assets/character_icons/gabon.svg",
  },
  {
    name: "ディディーコング",
    type: "スピード",
    stats: { speed: 5, power: 2.5, control: 2.5, spin: 3 },
    special: "スライスチャージ速度向上",
    text: "すばしっこくボールに追いつける。Bで打てるスライスを早くチャージできる",
    image: "assets/character_icons/diddy-kong.svg",
  },
  {
    name: "ワンワン",
    type: "パワー",
    stats: { speed: 2.5, power: 5, control: 3, spin: 0 },
    special: "スマッシュ返球時の押し出し無効",
    text: "かたい体はだれよりも重い。スマッシュでもふきとばされない。力まかせでショットは全く曲がらない",
    image: "assets/character_icons/wanwan.svg",
  },
  {
    name: "キャサリン",
    type: "オールラウンド",
    stats: { speed: 4, power: 3.5, control: 2.5, spin: 1.5 },
    special: "フラットチャージ速度向上",
    text: "安定したプレイでコート上を舞う。Yで打てるフラットを早くチャージできる",
    image: "assets/character_icons/catherine.svg",
  },
  {
    name: "パタパタ",
    type: "テクニック",
    stats: { speed: 4, power: 2, control: 5, spin: 2.5 },
    special: "ロブチャージ速度向上",
    text: "コート端ぎりぎりをねらうのが得意。A→Bで打てるロブを早くチャージできる",
    image: "assets/character_icons/patapata.svg",
  },
  {
    name: "ボスパックン",
    type: "パワー",
    stats: { speed: 2.5, power: 5, control: 3.5, spin: 1.5 },
    special: "フラットでNICEサーブ時強化、それ以外は弾速弱化。ストローク時、フラット強化",
    text: "NICEでフラットサーブが打てると最速だが失敗するとヘロヘロ球に。Y→Yで打つストロークが特に強い",
    image: "assets/character_icons/boss-packun.svg",
  },
  {
    name: "パックンフラワー",
    type: "トリッキー",
    stats: { speed: 3.0, power: 1, control: 4, spin: 1.5 },
    special: "トップが高弾道かつはねる",
    text: "鉢が重くてもテニスをしたい。全身をひねって打つトップスピンはだれよりも高弾道ではねる",
    image: "assets/character_icons/packun-flower.svg",
  },
  {
    name: "ブンブン",
    type: "ディフェンス",
    stats: { speed: 2, power: 4, control: 2.5, spin: 0.5 },
    special: "左右移動が速く、前後移動は遅い",
    text: "大きな両手で守備範囲が広い。左右の移動は速いが前後の移動はとてもおそいという弱点がある",
    image: "assets/character_icons/bunbun.svg",
  },
  {
    name: "ゲッソー",
    type: "トリッキー",
    stats: { speed: 3.5, power: 0.5, control: 3.5, spin: 4 },
    special: "スライスが高弾道",
    text: "バケツの水をあびてなんとか出場。やわらかい体で打ち出すスライスは高い弾道でするどく曲がる",
    image: "assets/character_icons/gesso.svg",
  },
  {
    name: "ほねクッパ",
    type: "ディフェンス",
    stats: { speed: 2, power: 4.5, control: 1, spin: 1 },
    special: "バックハンド時、スライス強化",
    text: "相手を圧倒するパワーは健在。バックハンドのスライスが強力でフォアハンドよりよく曲がる",
    image: "assets/character_icons/hone-koopa.svg",
  },
  {
  name: "カロン",
  type: "トリッキー",
  stats: { speed: 1.5, power: 3, control: 3, spin: 3.5 },
  special: "ドロップが曲がる",
  text: "コウラに入って移動するがノコノコとちがってけっこうおそい。B→Aのドロップショットが曲がる",
  image: "assets/character_icons/karon.svg",
  },
  {
    name: "ベビィマリオ",
    type: "オールラウンド",
    stats: { speed: 3.5, power: 2.5, control: 3, spin: 2.5 },
    special: "ドロップが曲がる",
    text: "ベビィのころのマリオ。すべての能力が安定して高い。足りないパワーはスピンでおぎなう",
    image: "assets/character_icons/baby-mario.svg",
  },
  {
    name: "ベビィルイージ",
    type: "オールラウンド",
    stats: { speed: 2.5, power: 3, control: 2.5, spin: 1.5 },
    special: "強打スライスボレー強化",
    text: "ベビィのころのルイージ。マリオと組むために練習したボレーが得意でB→Bのボレーが特に強い",
    image: "assets/character_icons/baby-luigi.svg",
  },
  {
    name: "ベビィピーチ",
    type: "テクニック",
    stats: { speed: 1, power: 1, control: 5, spin: 2 },
    special: "特になし",
    text: "ベビィのころのピーチ。コート端ぎりぎりに入るような精度の高いショットが得意",
    image: "assets/character_icons/wario.svg",
  },
  {
    name: "ハナチャン",
    type: "ディフェンス",
    stats: { speed: 5, power: 4, control: 1.5, spin: 0.5 },
    special: "切り替えしが苦手",
    text: "たくさんの足で前進するのが得意。スピードが乗ると速いものの方向転換はニガテで止まりづらい",
    image: "assets/character_icons/hana-chan.svg",
  },
  {
    name: "トッテン",
    type: "スピード",
    stats: { speed: 5, power: 1.5, control: 2.5, spin: 2.5 },
    special: "フォアハンド強化、バックハンド弱化",
    text: "逃げ足がとっても速い。フォアハンドのショットは強いが袋がジャマでバックハンドは弱い",
    image: "assets/character_icons/totten.svg",
  },
  {
    name: "クリボー",
    type: "オールラウンド",
    stats: { speed: 4, power: 2, control: 3.5, spin: 1.5 },
    special: "特になし",
    text: "簡単にやられがちなクッパの手下。ラケットくわえてテニスに挑戦。クリボーでもがんばれば勝てますか？",
    image: "assets/character_icons/kuribo.svg",
  },
  {
    name: "ベビィワリオ",
    type: "パワー",
    stats: { speed: 2.5, power: 4.5, control: 2, spin: 1 },
    special: "トップチャージ速度向上",
    text: "ベビィのころのワリオ。Aで打てるトップスピンを早くチャージできる",
    image: "assets/character_icons/baby-wario.svg",
  },
  {
    name: "ベビィワルイージ",
    type: "ディフェンス",
    stats: { speed: 1.5, power: 2, control: 1.5, spin: 2 },
    special: "フラットボレー強化",
    text: "ベビィのころのワルイージ。スライドフットワークで広く守る。Y→Yで打つボレーが特に強い",
    image: "assets/character_icons/baby-waluigi.svg",
  },
];

export const rackets = [
  {
    name: "ファイアラケット",
    category: "妨害",
    timing: "バウンド時",
    effect: "炎を5つ十字方向に設置。触れると短時間ショット不可 + 強制移動 + ダメージ。",
    text: "炎をコートにまきちらす。ふれるとアチチ！と走り回る。",
    image: "assets/racket_icons/fire_racket.svg",
  },
  {
    name: "アイスラケット",
    category: "妨害",
    timing: "即時",
    effect: "氷の床を設置。滑って切り替えししづらくなる。強打をすると短時間行動不可",
    text: "コートがツルツルに！強いショット打ち返すと転ぶ。",
    image: "assets/racket_icons/ice_racket.svg",
  },
  {
    name: "パワーラケット",
    category: "強化",
    timing: "即時",
    effect: "一定時間パワーが上昇し、スマッシュが強化される。",
    text: "一撃必殺の強打をサポートするパワー特化型。",
    image: "assets/racket_icons/power_racket.svg",
  },
  {
    name: "トリックラケット",
    category: "その他",
    timing: "バウンド時",
    effect: "ボールがバウンドすると変化が付き、予測しづらい軌道になる。",
    text: "予測不能なショットで相手のミスを誘う。",
    image: "assets/racket_icons/trick_racket.svg",
  },
];
